openapi: 3.0.0
info:
  title: VSCU - Collection
  description: ""
  version: 1.0.0
servers:
- url: http://20.94.40.140:8088
tags:
- name: VSCU- Basic Data Management
- name: VSCU-Branch information management
- name: VSCU-Imports Item Management
- name: VSCU-Initialization
- name: VSCU-Item Management
- name: VSCU-Purchase management
- name: VSCU-Sales Management
- name: VSCU-Stock Information Management
paths:
  /code/selectCodes:
    post:
      tags:
      - VSCU- Basic Data Management
      summary: 'Get code list '
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P000607989R
      - name: bhfId
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      - name: cmckey
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: D3B478EDFBE54536B8DC9DA691A51440E6278C18104D4D6D904F
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: P000607989R
                bhfId: "00"
                lastReqDt: "20230328000000"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
      security:
      - noauthAuth: []
  /itemClass/selectItemsClass:
    post:
      tags:
      - VSCU- Basic Data Management
      summary: 'Get item classification list '
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P000607989R
      - name: bhfid
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      - name: cmckey
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: D3B478EDFBE54536B8DC9DA691A51440E6278C18104D4D6D904F
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: 'A123456789Z '
                bhfId: "00"
                lastReqDt: "20180523000000"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /customers/selectCustomer:
    post:
      tags:
      - VSCU- Basic Data Management
      summary: Get all PIN list
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P000607989R
      - name: bhfid
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      - name: cmckey
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: D3B478EDFBE54536B8DC9DA691A51440E6278C18104D4D6D904F
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: A123456789Z
                bhfId: "00"
                custmTin: A987654321Z
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /branches/selectBranches:
    post:
      tags:
      - VSCU- Basic Data Management
      summary: 'Get branch list  '
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P000607989R
      - name: bhfid
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      - name: cmckey
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: D3B478EDFBE54536B8DC9DA691A51440E6278C18104D4D6D904F
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: A123456789Z
                bhfId: "00"
                lastReqDt: "20180520000000"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /notices/selectNotices:
    post:
      tags:
      - VSCU- Basic Data Management
      summary: 'Get notice list '
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P000607989R
      - name: bhfid
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      - name: cmckey
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: D3B478EDFBE54536B8DC9DA691A51440E6278C18104D4D6D904F
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: A123456789Z
                bhfId: "00"
                lastReqDt: "20180520000000"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /branches/saveBrancheCustomers:
    post:
      tags:
      - VSCU-Branch information management
      summary: Send customer information
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P000607989R
      - name: bhfid
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      - name: cmckey
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: D3B478EDFBE54536B8DC9DA691A51440E6278C18104D4D6D904F
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: P123456789Z
                bhfId: "00"
                custNo: "999991113"
                custTin: A123456789Z
                custNm: MTEJA LIMITED
                useYn: "Y"
                regrNm: Admin
                regrId: Admin
                modrNm: Admin
                modrId: Admin
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /branches/saveBrancheUsers:
    post:
      tags:
      - VSCU-Branch information management
      summary: Send branch user account
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P000607989R
      - name: bhfid
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      - name: cmckey
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: D3B478EDFBE54536B8DC9DA691A51440E6278C18104D4D6D904F
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: P123456789Z
                bhfId: "00"
                userId: userId3
                userNm: UserName3
                pwd: "12341234"
                useYn: "Y"
                regrNm: Admin
                regrId: Admin
                modrNm: Admin
                modrId: Admin
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /branches/saveBrancheInsurances:
    post:
      tags:
      - VSCU-Branch information management
      summary: 'Send branch insurance information '
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P000607989R
      - name: bhfid
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      - name: cmckey
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: D3B478EDFBE54536B8DC9DA691A51440E6278C18104D4D6D904F
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: P123456789Z
                bhfId: "00"
                isrccCd: ISRCC01
                isrccNm: RSSB Insurance
                isrcRt: 20
                useYn: "Y"
                regrNm: Admin
                regrId: Admin
                modrNm: Admin
                modrId: Admin
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /imports/selectImportItems:
    post:
      tags:
      - VSCU-Imports Item Management
      summary: Get imported item information
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P000607989R
      - name: bhfid
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      - name: cmckey
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: D3B478EDFBE54536B8DC9DA691A51440E6278C18104D4D6D904F
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: P123456789Z
                bhfId: "00"
                lastReqDt: "20190524000000"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /imports/updateImportItems:
    post:
      tags:
      - VSCU-Imports Item Management
      summary: 'Send (converted) imported item information '
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P000607989R
      - name: bhfid
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      - name: cmckey
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: D3B478EDFBE54536B8DC9DA691A51440E6278C18104D4D6D904F
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: P123456789Z
                bhfId: "00"
                taskCd: "2231943"
                dclDe: "20191217"
                itemSeq: 1
                hsCd: "1231531231"
                itemClsCd: "5022110801"
                itemCd: KE1NTXU0000001
                imptItemSttsCd: "1"
                remark: remark
                modrNm: Admin
                modrId: Admin
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /initializer/selectInitInfo:
    post:
      tags:
      - VSCU-Initialization
      summary: Initialization Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: A123456789Z
                bhfId: "00"
                dvcSrlNo: dvcv1130
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /items/saveItems:
    post:
      tags:
      - VSCU-Item Management
      summary: Send Item information
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P000607989R
      - name: bhfid
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      - name: cmckey
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: D3B478EDFBE54536B8DC9DA691A51440E6278C18104D4D6D904F
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: P000607989R
                bhfId: "00"
                itemCd: KE1NTXU0000006
                itemClsCd: "5059690800"
                itemTyCd: "1"
                itemNm: test materialitem 3
                orgnNatCd: KE
                pkgUnitCd: NT
                qtyUnitCd: U
                taxTyCd: B
                dftPrc: 3500
                grpPrcL1: 3500
                grpPrcL2: 3500
                grpPrcL3: 3500
                grpPrcL4: 3500
                isrcAplcbYn: "N"
                useYn: "Y"
                regrNm: Admin
                regrId: Admin
                modrNm: Admin
                modrId: Admin
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /items/selectItems:
    post:
      tags:
      - VSCU-Item Management
      summary: Get Item information
      parameters:
      - name: tin
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: P000607989R
      - name: bhfid
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
        example: "00"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: P123456789Z
                bhfId: "00"
                lastReqDt: "20160523000000"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /items/saveItemComposition:
    post:
      tags:
      - VSCU-Item Management
      summary: Send Item Composition
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: P051402798L
                bhfId: "01"
                itemCd: KE1NTXU0000008
                cpstItemCd: ITM001
                cpstQty: 10
                regrId: Admin
                regrNm: Admin
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /trnsPurchase/selectTrnsPurchaseSales:
    post:
      tags:
      - VSCU-Purchase management
      summary: Get purchase transaction information
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P000607989R
      - name: bhfid
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: P123456789Z
                bhfId: "00"
                lastReqDt: "20190524000000"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /trnsPurchase/savePurchases:
    post:
      tags:
      - VSCU-Purchase management
      summary: Send purchase transaction information
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P000607989R
      - name: bhfid
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: P123456789Z
                bhfId: "00"
                invcNo: 1
                orgInvcNo: 0
                regTyCd: M
                pchsTyCd: "N"
                rcptTyCd: P
                pmtTyCd: "01"
                pchsSttsCd: "02"
                cfmD t: "20200127210300"
                pchsDt: "20200127"
                wrhsDt: ""
                cnclReqDt: ""
                cnclDt: ""
                rfdDt: ""
                totItemCnt: 2
                taxblAmtA: 0
                taxblAmtB: 250000
                taxblAmtC: 0
                taxblAmtD: 0
                taxblAmtE: 0
                taxRtA: 0
                taxRtB: 18
                taxRtC: 0
                ta xRtD: 0
                taxRtE: 0
                taxAmtA: 0
                taxAmtB: 94576
                taxAmtC: 0
                taxAmtD: 0
                taxAmtE: 0
                totTaxblAmt: 10500
                totTaxAmt: 1890
                totAmt: 10500
                regrNm: Admin
                regrId: Admin
                modrNm: Admin
                modrId: Admin
                itemList:
                - itemSeq: 1
                  itemCd: KE1NTXU0000001
                  itemClsCd: "5059690800"
                  itemNm: test item 1
                  bcd: ""
                  pkgUnitCd: NT
                  pkg: 2
                  qtyUnitCd: U
                  qty: 2
                  prc: 3500
                  splyAmt: 7000
                  dcRt: 0
                  dcAmt: 0
                  taxblAmt: 7000
                  taxTyCd: B
                  taxAmt: 1260
                  totAmt: 7000
                - itemSeq: 2
                  itemCd: KE1NTXU0000002
                  itemClsCd: "5022110801"
                  itemNm: test item 2
                  bcd: ""
                  pkgUnitCd: NT
                  pkg: 1
                  qtyUnitCd: U
                  qty: 1
                  prc: 3500
                  splyAmt: 3500
                  dcRt: 0
                  dcAmt: 0
                  taxblAmt: 3500
                  taxTyCd: B
                  taxAmt: 6.3
                  totAmt: 3500
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /trnsSales/saveSales:
    post:
      tags:
      - VSCU-Sales Management
      summary: Send sales transaction information
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P051109164C
      - name: bhfid
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      - name: cmckey
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: D3B478EDFBE54536B8DC9DA691A51440E6278C18104D4D6D904F
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: P000607989R
                bhfId: "00"
                invcNo: 1
                orgInvcNo: 0
                custTin: A123456789Z
                custNm: Miriam
                salesTyCd: "N"
                rcptTyCd: S
                pmtTyCd: "01"
                salesSttsCd: "02"
                cfmDt: "20210709120300"
                salesDt: "20230328"
                stockRlsDt: "20210709120300"
                totItemCnt: 2
                taxblAmtA: 0
                taxblAmtB: 250000
                taxblAmtC: 0
                taxblAmtD: 0
                taxblAmtE: 0
                taxRtA: 0
                taxRtB: 16
                taxRtC: 0
                taxRtD: 0
                taxRtE: 0
                taxAmtA: 0
                taxAmtB: 94576
                taxAmtC: 0
                taxAmtD: 0
                taxAmtE: 0
                totTaxblAmt: 250000
                totTaxAmt: 38135
                totAmt: 250000
                prchrAcptcYn: "N"
                regrId: "11999"
                regrNm: TestVSCU
                modrId: "45678"
                modrNm: TestVSCU
                receipt:
                  custTin: "100110263"
                  rptNo: 1
                  trdeNm: ""
                  adrs: ""
                  topMsg: Shopwithus
                  btmMsg: Welcome
                  prchrAcptcYn: "N"
                itemList:
                - ' itemSeq': 1
                  itemCd: KE1NTXU0000001
                  itemClsCd: "5059690800"
                  itemNm: OutDoorUnit
                  pkgUnitCd: NT
                  pkg: 1
                  qtyUnitCd: U
                  qty: 1
                  prc: 200000
                  splyAmt: 200000
                  dcRt: 0
                  dcAmt: 0
                  taxTyCd: B
                  taxblAmt: 200000
                  taxAmt: 30508
                  totAmt: 200000
                - itemSeq: 2
                  itemCd: KE1NTXU0000002
                  itemClsCd: "5022110801"
                  itemNm: NetworkCable
                  pkgUnitCd: NT
                  pkg: 1
                  qtyUnitCd: U
                  qty: 1
                  prc: 50000
                  splyAmt: 50000
                  dcRt: 0
                  dcAmt: 0
                  taxTyCd: B
                  taxblAmt: 50000
                  taxAmt: 7627
                  totAmt: 50000
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /stock/selectStockItems:
    post:
      tags:
      - VSCU-Stock Information Management
      summary: Move Stock Request
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P000607989R
      - name: bhfid
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: P123456789Z
                bhfId: "00"
                lastReqDt: "20180524000000"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /stock/saveStockItems:
    post:
      tags:
      - VSCU-Stock Information Management
      summary: Send Stock Information
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P000607989R
      - name: bhfid
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: P123456789Z
                bhfId: "00"
                sarNo: 2
                orgSarNo: 2
                regTyCd: M
                sarTyCd: "11"
                ocrnDt: "20200126"
                totItemCnt: 2
                totTaxblAmt: 70000
                totTaxAmt: 12000
                totAmt: 70000
                regrId: Admin
                regrNm: Admin
                modrNm: Admin
                modrId: Admin
                itemList:
                - itemSeq: 1
                  itemCd: KE1NTXU0000001
                  itemClsCd: "5059690800"
                  itemNm: testitem1
                  pkgUnitCd: NI
                  pkg: 10
                  qtyUnitCd: U
                  qty: 10
                  prc: 3500
                  splyAmt: 35000
                  totDcAmt: 0
                  taxblAmt: 35000
                  taxTyCd: B
                  taxAmt: 6000
                  totAmt: 35000
                - itemSeq: 2
                  itemCd: KE1NTXU0000002
                  itemClsCd: "5059690800"
                  itemNm: test item2
                  pkgUnitCd: NI
                  pkg: 10
                  qtyUnitCd: U
                  qty: 10
                  prc: 3500
                  splyAmt: 35000
                  totDcAmt: 0
                  taxblAmt: 35000
                  taxTyCd: B
                  taxAmt: 6000
                  totAmt: 35000
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /stockMaster/saveStockMaster:
    post:
      tags:
      - VSCU-Stock Information Management
      summary: Stock Master Save Request
      parameters:
      - name: tin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: P000607989R
      - name: bhfid
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: integer
        example: "00"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tin: P123456789Z
                bhfId: "00"
                itemCd: KE1NTXU0000002
                rsdQty: 10
                regrId: Admin
                regrNm: Admin
                modrNm: Admin
                modrId: Admin
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
components:
  schemas: {}
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
